# \bibliography{./bibliography}
#+TITLE: Grafy i Sieci: Porównanie algorytmów znajdowania maksymalnej kliki w grafie
#+AUTHOR: Marek Lewandowski, Juliusz Gonera
#+DATE:
#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{biblatex}
#+LaTeX_HEADER: \bibliography{bibliography}

* Problem maksymalnej kliki
  Kliką nazywamy spójny podgraf, taki że nie jest on zawarty w żadnym innym spójnym podgrafie. 
  Maksymalna klika to klika składająca się z największej liczby wierzchołków. 
  Problem znajdowania maksymalnej kliki w grafie jest problemem NP-zupełnym.
* Algorytm
  Do zaimplementowania został wybrany algorytm Brona-Kerboscha\cite{kerbosch} w wersji bez pivotingu. Zostanie on porównany z dostępną implementacją w bibliotece JGraphT\cite{jgrapht}.
* Technologia
  Program zostanie zaimplementowany w języku Scala. Jest to statycznie typowany język działający na JVM, w pełni kompatybilny z językiem Java.
* Testy
  Częścią projektu jest opracowanie danych testowych na których zostanie zbadana poprawność jak i czas wykonania algorytmów.

\printbibliography
