# \bibliography{./bibliography}
#+TITLE: Porównanie algorytmów znajdowania maksymalnej kliki w grafie
#+AUTHOR: Marek Lewandowski, Juliusz Gonera
#+DATE:
#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{biblatex}
#+LaTeX_HEADER: \bibliography{bibliography}

* Problem maksymalnej kliki
  Kliką nazywamy spójny podgraf, taki że nie jest on zawarty w żadnym innym spójnym podgrafie. 
  Maksymalna klika to klika składająca się z największej liczby wierzchołków. 
  Problem znajdowania maksymalnej kliki w grafie jest problemem NP-zupełnym.
* Algorytm
  Do zaimplementowania został wybrany algorytm opisany w \cite{bioinf} (Fig. 2). Zostanie on porównany z dostępną implementacją algorytmu Brona-Kerboscha w bibliotece JGraphT\cite{jgrapht}.
* Technologia
  Program zostanie zaimplementowany w języku Scala. Jest to statycznie typowany język działający na JVM, w pełni kompatybilny z językiem Java.
* Testy
Do testowania poprawności i empirycznego porównania wydajności algorytmów zostanie użyty DIMACS Benchmark Set\cite{dimacs}. Jest to zbiór nietrywialnych grafów dla których znana jest liczba wierzchołków tworzących maksymalną klikę w grafie.

\printbibliography
